import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface KaryawanResult {
  id: string;
  amanah: number;
  kompeten: number;
  harmonis: number;
  loyal: number;
  adaptif: number;
  kolaboratif: number;
  nilaiAkhir: number;
  calculatedAt: Date | string;
  karyawan: {
    id: string;
    nama: string;
    jabatan: string;
    divisi: string;
  };
}

interface BreakdownItem {
  jenis: string;
  count: number;
  scores: Record<string, number>;
}

interface DetailedResult {
  result: KaryawanResult;
  breakdown: BreakdownItem[];
  totalAssessments: number;
}

const INDICATOR_LABELS: Record<string, string> = {
  AMANAH: "Amanah",
  KOMPETEN: "Kompeten",
  HARMONIS: "Harmonis",
  LOYAL: "Loyal",
  ADAPTIF: "Adaptif",
  KOLABORATIF: "Kolaboratif",
};

const JENIS_LABELS: Record<string, string> = {
  SELF: "Self Assessment",
  ATASAN: "Penilaian Atasan",
  REKAN_KERJA: "Penilaian Rekan Kerja",
  BAWAHAN: "Penilaian Bawahan",
};

export function generateLaporanPDF(results: KaryawanResult[], title?: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(22, 163, 74); // Green
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("PT ENERGI NUSANTARA", pageWidth / 2, 15, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Laporan Penilaian Kinerja AKHLAK 360°", pageWidth / 2, 24, {
    align: "center",
  });

  if (title) {
    doc.setFontSize(10);
    doc.text(title, pageWidth / 2, 31, { align: "center" });
  }

  // Date
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  const dateStr = new Date().toLocaleDateString("id-ID", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(`Dicetak: ${dateStr}`, 14, 45);

  // Summary
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`Total Karyawan Dinilai: ${results.length}`, 14, 53);

  // Table
  const tableHeaders = [
    "No",
    "Nama",
    "Jabatan",
    "Divisi",
    "A",
    "K",
    "H",
    "L",
    "A",
    "K",
    "Nilai Akhir",
  ];

  const tableData = results.map((r, i) => [
    i + 1,
    r.karyawan.nama,
    r.karyawan.jabatan,
    r.karyawan.divisi,
    r.amanah.toFixed(2),
    r.kompeten.toFixed(2),
    r.harmonis.toFixed(2),
    r.loyal.toFixed(2),
    r.adaptif.toFixed(2),
    r.kolaboratif.toFixed(2),
    r.nilaiAkhir.toFixed(2),
  ]);

  autoTable(doc, {
    startY: 58,
    head: [tableHeaders],
    body: tableData,
    foot: [["", "", "", "", "", "", "", "", "", "", ""]],
    theme: "striped",
    headStyles: {
      fillColor: [22, 163, 74],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 35 },
      2: { cellWidth: 30 },
      3: { cellWidth: 20 },
      4: { cellWidth: 12 },
      5: { cellWidth: 12 },
      6: { cellWidth: 12 },
      7: { cellWidth: 12 },
      8: { cellWidth: 12 },
      9: { cellWidth: 12 },
      10: { cellWidth: 18, fontStyle: "bold" },
    },
    didParseCell: (data) => {
      // Color code nilai columns
      if (data.column.index >= 4 && data.column.index <= 10 && data.section === "body") {
        const value = parseFloat(data.cell.raw as string);
        if (!isNaN(value)) {
          if (value < 3) {
            data.cell.styles.textColor = [220, 38, 38]; // Red
          } else if (value >= 3 && value < 4) {
            data.cell.styles.textColor = [217, 119, 6]; // Amber
          } else {
            data.cell.styles.textColor = [22, 163, 74]; // Green
          }
        }
      }
    },
    didDrawPage: (data) => {
      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
          `Halaman ${i} dari ${pageCount}`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: "center" }
        );
        doc.text(
          "Generated by SIMKK - PT Energi Nusantara",
          14,
          doc.internal.pageSize.getHeight() - 10
        );
      }
    },
  });

  // Save
  const fileName = `Laporan_AKHLAK_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
}

export function generateSingleEmployeePDF(data: DetailedResult) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(22, 163, 74);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("PT ENERGI NUSANTARA", pageWidth / 2, 15, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Detail Penilaian Kinerja Karyawan", pageWidth / 2, 24, {
    align: "center",
  });

  let yPos = 48;

  // Employee Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Data Karyawan", 14, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Nama: ${data.result.karyawan.nama}`, 14, yPos);
  yPos += 6;
  doc.text(`Jabatan: ${data.result.karyawan.jabatan}`, 14, yPos);
  yPos += 6;
  doc.text(`Divisi: ${data.result.karyawan.divisi}`, 14, yPos);
  yPos += 6;
  doc.text(`Total Penilaian: ${data.totalAssessments}`, 14, yPos);
  yPos += 6;
  doc.text(
    `Tanggal Kalkulasi: ${new Date(data.result.calculatedAt).toLocaleDateString("id-ID")}`,
    14,
    yPos
  );
  yPos += 15;

  // Overall Score
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("NILAI AKHIR", 14, yPos);
  doc.setFontSize(24);
  doc.setTextColor(22, 163, 74);
  doc.text(data.result.nilaiAkhir.toFixed(2), 70, yPos);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text("/ 5.00", 95, yPos);
  yPos += 15;

  // AKHLAK Scores Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Skor Per Indikator AKHLAK", 14, yPos);
  yPos += 8;

  const skorHeaders = ["Indikator", "Skor", "Keterangan"];
  const skorData = [
    ["Amanah", data.result.amanah.toFixed(2), ""],
    ["Kompeten", data.result.kompeten.toFixed(2), ""],
    ["Harmonis", data.result.harmonis.toFixed(2), ""],
    ["Loyal", data.result.loyal.toFixed(2), ""],
    ["Adaptif", data.result.adaptif.toFixed(2), ""],
    ["Kolaboratif", data.result.kolaboratif.toFixed(2), ""],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [skorHeaders],
    body: skorData,
    theme: "striped",
    headStyles: {
      fillColor: [22, 163, 74],
      textColor: [255, 255, 255],
    },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 30, halign: "center" },
      2: { cellWidth: "auto" },
    },
    didParseCell: (cellData) => {
      if (cellData.column.index === 1 && cellData.section === "body") {
        const value = parseFloat(cellData.cell.raw as string);
        if (value < 3) {
          cellData.cell.styles.textColor = [220, 38, 38];
        } else if (value >= 3 && value < 4) {
          cellData.cell.styles.textColor = [217, 119, 6];
        } else {
          cellData.cell.styles.textColor = [22, 163, 74];
        }
        cellData.cell.styles.fontStyle = "bold";
      }
    },
  });

  // Breakdown by Jenis (if exists)
  if (data.breakdown.length > 0) {
    yPos = (doc as any).lastAutoTable.finalY + 15;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Rincian Per Jenis Penilaian", 14, yPos);
    yPos += 8;

    const jenisHeaders = ["Jenis Penilaian", "Jumlah", "A", "K", "H", "L", "A", "K"];
    const jenisData = data.breakdown.map((b) => [
      JENIS_LABELS[b.jenis] || b.jenis,
      b.count,
      (b.scores["AMANAH"] || 0).toFixed(2),
      (b.scores["KOMPETEN"] || 0).toFixed(2),
      (b.scores["HARMONIS"] || 0).toFixed(2),
      (b.scores["LOYAL"] || 0).toFixed(2),
      (b.scores["ADAPTIF"] || 0).toFixed(2),
      (b.scores["KOLABORATIF"] || 0).toFixed(2),
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [jenisHeaders],
      body: jenisData,
      theme: "striped",
      headStyles: {
        fillColor: [22, 163, 74],
        textColor: [255, 255, 255],
        fontSize: 8,
      },
      bodyStyles: {
        fontSize: 8,
      },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Halaman ${i} dari ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
    doc.text(
      "Generated by SIMKK - PT Energi Nusantara",
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  const fileName = `Penilaian_${data.result.karyawan.nama.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
}
